export { default as signPng } from '@/resource/images/sign.png'
export { default as noticePng } from '@/resource/images/notice.png'
export { default as flowPng } from '@/resource/images/flow.png'
export { default as locationPng } from '@/resource/images/location.png'
export { default as knowledgePng } from '@/resource/images/knowledge.png'
export { default as cameraPng } from '@/resource/images/camera.png'
